name: Pre-commit checks

on:
  pull_request:

jobs:
  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Fetch target branch
        run: |
          git fetch origin ${{ github.event.pull_request.head.sha }}
          git fetch origin ${{ github.event.pull_request.base.sha }}
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
